-- Indexes for primary keys have been explicitly created.

DROP TABLE User;
DROP TABLE Transport;
DROP TABLE Activity;
DROP TABLE Accommodation;
DROP TABLE Travel;
DROP Table Transport;

CREATE TABLE User (
    id BIGINT NOT NULL AUTO_INCREMENT,
    email VARCHAR(60) NOT NULL,
    password VARCHAR(60) NOT NULL, 
    firstName VARCHAR(60) NOT NULL,
    lastName VARCHAR(60) NOT NULL, 
    role TINYINT NOT NULL,
    CONSTRAINT UserPK PRIMARY KEY (id),
    CONSTRAINT EmailUniqueKey UNIQUE (email)
) ENGINE = InnoDB;

CREATE TABLE Transport (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(60) NOT NULL,
    CONSTRAINT TransportPK PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE Travel (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(60) NOT NULL,
    CONSTRAINT TravelPK PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE Activity (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(60) NOT NULL,
	CONSTRAINT ActivityPK PRIMARY KEY (id)
) ENGINE = InnoDB;

CREATE TABLE Accommodation (
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(60) NOT NULL,
	CONSTRAINT AcommodationPK PRIMARY KEY (id)
) ENGINE = InnoDB;